Controllers/DriversController.cs
using Microsoft.AspNetCore.Mvc;
using CarManagement.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace CarManagement.Controllers
{
    [Authorize]
    public class DriversController : Controller
    {
        private readonly DriversRepository _repository;

        public DriversController(DriversRepository repository)
        {
            _repository = repository;
        }

        // GET: Drivers
        public async Task<IActionResult> Index()
        {
            IEnumerable<Driver> drivers = await _repository.GetAllDrivers();
            return View(drivers);
        }

        // GET: Drivers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _repository.Details(id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // GET: Drivers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Drivers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Driver driver)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _repository.Create(driver);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Show the error message to the user
                    ModelState.AddModelError(string.Empty, "A Driver with the same Licence Number already exists.");
                }
            }
            return View(driver);
        }

        // GET: Drivers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _repository.Details(id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // POST: Drivers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Driver driver)
        {
            if (id != driver.DriverId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await _repository.Edit(id, driver);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Show the error message to the user
                    ModelState.AddModelError(string.Empty, "A Driver with the same Licence Number already exists.");
                }
            }
            return View(driver);
        }

        // GET: Drivers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _repository.Details(id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _repository.Delete(id);
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/MaintenancesController.cs
using CarManagement.Models;
using CarManagement.Repositories;
using CarManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarManagement.Controllers
{
    [Authorize]
    public class MaintenancesController : Controller
    {
        private readonly MaintenanceRepository _maintenanceRepository;
        private readonly VehicleRepository _vehicleRepository;

        public MaintenancesController(MaintenanceRepository maintenanceRepository, VehicleRepository vehicleRepository)
        {
            _maintenanceRepository = maintenanceRepository;
            _vehicleRepository = vehicleRepository;
        }

        // GET: Maintenances
        public async Task<IActionResult> Index()
        {
            var maintenances = await _maintenanceRepository.GetAllMaintenances();
            return View(maintenances);
        }

        public async Task<IActionResult> MaintenancebyVehicle(int id)
        {
            var vehicle = await _vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            var maintenances = await _maintenanceRepository.GetAllMaintenancesByVehicleId(id);
            var viewModel = new MaintenancesViewModel
            {
                VehicleId = id,
                maintenances = maintenances
            };
            ViewData["Vehiclepltnb"] = vehicle.PlateNumber;
            return View("MaintenancebyId", viewModel);
        }

        // GET: Maintenances/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenance = await _maintenanceRepository.GetMaintenanceDetails(id);
            if (maintenance == null)
            {
                return NotFound();
            }

            return View(maintenance);
        }

        // GET: Maintenances/Create/1
        public async Task<IActionResult> Create(int id)
        {
            var vehicle = await _vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            ViewBag.Vehicles = new SelectList(await _vehicleRepository.GetallVehicles(), "VehicleId", "PlateNumber");
            var model = new MaintenancesViewModel
            {
                VehicleId = id,
                maintenance = new Maintenance(),
                maintenances = new List<Maintenance>()
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MaintenancesViewModel model)
        {
            if (ModelState.IsValid)
            {
                var vehicle = await _vehicleRepository.Details(model.VehicleId);
                if (vehicle == null)
                {
                    return NotFound();
                }

                var maintenance = new Maintenance
                {
                    Description = model.maintenance.Description,
                    DateOfMaintenance = model.maintenance.DateOfMaintenance,
                    Cost = model.maintenance.Cost,
                    VehicleId = model.VehicleId
                };

                await _maintenanceRepository.CreateMaintenance(maintenance);

                return RedirectToAction(nameof(MaintenancebyVehicle), new { id = maintenance.VehicleId });
            }

            return View(model);
        }

        // GET: Maintenances/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenance = await _maintenanceRepository.GetMaintenanceDetails(id);
            if (maintenance == null)
            {
                return NotFound();
            }

            ViewData["VehicleId"] = new SelectList(await _vehicleRepository.GetallVehicles(), "VehicleId", "PlateNumber", maintenance.VehicleId);
            return View(maintenance);
        }

        // POST: Maintenances/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Maintenance maintenance)
        {
            if (id != maintenance.MaintenanceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _maintenanceRepository.EditMaintenance(id, maintenance);
                return RedirectToAction(nameof(MaintenancebyVehicle), new { id = maintenance.VehicleId });
            }

            ViewData["VehicleId"] = new SelectList(await _vehicleRepository.GetallVehicles(), "VehicleId", "PlateNumber", maintenance.VehicleId);
            return View("MaintenancebyId", maintenance);
        }

        // GET: Maintenances/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenance = await _maintenanceRepository.GetMaintenanceDetails(id);
            if (maintenance == null)
            {
                return NotFound();
            }

            return View(maintenance);
        }

        // POST: Maintenances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var maintenance = await _maintenanceRepository.GetMaintenanceDetails(id);

            if (ModelState.IsValid)
            {
                await _maintenanceRepository.DeleteMaintenance(id);
            }

            return RedirectToAction(nameof(MaintenancebyVehicle), new { id = maintenance.VehicleId });
        }
    }
}

Controllers/VehicleDriverHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CarManagement.Models;
using CarManagement.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace CarManagement.Controllers
{
    [Authorize]
    public class VehicleDriverHistoriesController : Controller
    {
        private readonly VehicleDriverHistoryRepository vehicleDriverHistoryRepository;
        private readonly VehicleRepository vehicleRepository;
        private readonly DriversRepository driversRepository;

        public VehicleDriverHistoriesController(VehicleDriverHistoryRepository vehicleDriverHistoryRepository, VehicleRepository vehicleRepository, DriversRepository driversRepository)
        {
            this.vehicleRepository = vehicleRepository;
            this.driversRepository = driversRepository;
            this.vehicleDriverHistoryRepository = vehicleDriverHistoryRepository;
        }

        // GET: VehicleDriverHistories
        //public IActionResult Index()
        //{
        //    var vehicleDriverHistories = vehicleDriverHistoryRepository.GetAllVehicleDriverHistories();
        //    return View(vehicleDriverHistories);
        //}

        public async Task<IActionResult> HistorybyvehicleId(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            ViewData["VehicleId"] = id;
            ViewData["Vehiclepltnb"] = vehicle.PlateNumber;
            var vehicleDriverHistories = await vehicleDriverHistoryRepository.GetVehicleDriverHistoriesByVehicleId(id);
            return View("Index", vehicleDriverHistories);
        }

        // GET: VehicleDriverHistories/DriverHistory/5
        public async Task<IActionResult> DriverHistory(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await driversRepository.Details(id.Value);
            if (driver == null)
            {
                return NotFound();
            }

            // Set the driver's license number and driver ID in the ViewData for the view
            ViewData["DriverLicenseNb"] = driver.LicenseNumber;
            ViewData["DriverId"] = driver.DriverId;

            var history = await vehicleDriverHistoryRepository.GetVehicleDriverHistoriesByDriverId(id.Value);

            return View(history);  // Return the view with the driver's history
        }

        // GET: VehicleDriverHistories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleDriverHistory = await vehicleDriverHistoryRepository.GetVehicleDriverHistoryDetails(id);
            if (vehicleDriverHistory == null)
            {
                return NotFound();
            }

            return View(vehicleDriverHistory);
        }

        //// GET: VehicleDriverHistories/Create
        //public IActionResult Create(int id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    var vehicle = vehicleRepository.Details(id);
        //    if (vehicle == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["DriverId"] = new SelectList(driversRepository.GetAllDrivers(), "DriverId", "Name");
        //    VehicleDriverHistory history = new VehicleDriverHistory
        //    {
        //        VehicleId = id
        //    };
        //    return View(history);
        //}

        //// POST: VehicleDriverHistories/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Create(VehicleDriverHistory vehicleDriverHistory)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        Console.WriteLine(vehicleDriverHistory.VehicleId);
        //        var vehicle = vehicleRepository.Details(vehicleDriverHistory.VehicleId);
        //        if (vehicle == null)
        //        {
        //            return NotFound();
        //        }
        //        vehicleDriverHistoryRepository.CreateVehicleDriverHistory(vehicleDriverHistory);
        //        return RedirectToAction(nameof(HistorybyvehicleId), new { id = vehicle.VehicleId });
        //    }
        //    ViewData["DriverId"] = new SelectList(driversRepository.GetAllDrivers(), "DriverId", "Name", vehicleDriverHistory.DriverId);
        //    return View(vehicleDriverHistory);
        //}

        // GET: VehicleDriverHistories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleDriverHistory = await vehicleDriverHistoryRepository.GetVehicleDriverHistoryDetails(id);
            if (vehicleDriverHistory == null)
            {
                return NotFound();
            }

            ViewData["DriverId"] = new SelectList(await driversRepository.GetAllDrivers(), "DriverId", "Name", vehicleDriverHistory.DriverId);
            return View(vehicleDriverHistory);
        }

        // POST: VehicleDriverHistories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, VehicleDriverHistory vehicleDriverHistory)
        {
            if (id != vehicleDriverHistory.VehicleDriverHistoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await vehicleDriverHistoryRepository.EditVehicleDriverHistory(id, vehicleDriverHistory);
                }
                catch (Exception)
                {
                    var vehiclehistory = await vehicleDriverHistoryRepository.GetVehicleDriverHistoryDetails(id);
                    if (vehiclehistory == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(HistorybyvehicleId), new { id = vehicleDriverHistory.VehicleId });
            }

            ViewData["DriverId"] = new SelectList(await driversRepository.GetAllDrivers(), "DriverId", "Name", vehicleDriverHistory.DriverId);
            return View(vehicleDriverHistory);
        }

        // GET: VehicleDriverHistories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleDriverHistory = await vehicleDriverHistoryRepository.GetVehicleDriverHistoryDetails(id);
            if (vehicleDriverHistory == null)
            {
                return NotFound();
            }

            return View(vehicleDriverHistory);
        }

        // POST: VehicleDriverHistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicleDriverHistory = await vehicleDriverHistoryRepository.GetVehicleDriverHistoryDetails(id);

            if (vehicleDriverHistory.EndDate == null)
            {
                ModelState.AddModelError(string.Empty, "You cannot delete this record because the driver is currently assigned. Please change the current driver before deleting.");
                return View(vehicleDriverHistory);
            }

            await vehicleDriverHistoryRepository.DeleteVehicleDriverHistory(id);
            return RedirectToAction(nameof(HistorybyvehicleId), new { id = vehicleDriverHistory.VehicleId });
        }
    }
}

Views/Vehicles/Create.cshtml
@model CarManagement.Models.Vehicle

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Vehicle</h4>
<hr />
<div class="row">
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <p>@error.ErrorMessage</p>
            }
        </div>
    }
    <div class="col-md-4">
        <form asp-action="Create">

            <div class="form-group">
                <label asp-for="PlateNumber" class="control-label"></label>
                <input asp-for="PlateNumber" class="form-control" />
                <span asp-validation-for="PlateNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfSeats" class="control-label"></label>
                <input asp-for="NumberOfSeats" class="form-control" />
                <span asp-validation-for="NumberOfSeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <br />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Vehicles/Delete.cshtml
@model CarManagement.Models.Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            PlateNumber
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlateNumber)
        </dd>
        <dt class="col-sm-2">
            NumberOfSeats)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfSeats)
        </dd>
        <dt class="col-sm-2">
            Color
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class="col-sm-2">
            Type
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="VehicleId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="VehicleDriverHistories" asp-action="HistorybyvehicleId" class="btn btn-success" asp-route-id="@Model?.VehicleId">Back to List</a>
    </form>
</div>

Views/Vehicles/Details.cshtml
@model CarManagement.Models.Vehicle

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Vehicle : @Html.DisplayFor(model => model.PlateNumber)</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            PlateNumber
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlateNumber)
        </dd>
        <dt class="col-sm-2">
            NumberOfSeats
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfSeats)
        </dd>
        <dt class="col-sm-2">
            Color
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class="col-sm-2">
            Type
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            Current Driver License Number
        </dt>
        <dd class="col-sm-10">
            @if (Model.CurrentDriverId != null)
            {
                @Html.DisplayFor(model => model.CurrentDriver.LicenseNumber)
            }
            else
            {
                <span>No current</span>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-success" asp-route-id="@Model?.VehicleId">Edit</a> |
    <a class="btn btn-primary" asp-action="Index">Back to List</a> |
    <a asp-controller="VehicleDriverHistories" asp-action="HistorybyvehicleId" class="btn btn-success" asp-route-id="@Model?.VehicleId">Drivers History</a>
</div>

Views/Vehicles/Edit.cshtml
@model CarManagement.Models.Vehicle

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Vehicle <input type="hidden" id="plateNumberHidden" value="@Model.PlateNumber" /></h4>
<hr />
<div class="row">
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <p>@error.ErrorMessage</p>
            }
        </div>
    }
    <div class="col-md-4">
        <form id="editVehicleForm" asp-action="Edit">

            <input type="hidden" asp-for="VehicleId" />
            <div class="form-group">
                <label asp-for="PlateNumber" class="control-label"></label>
                <input asp-for="PlateNumber" class="form-control" />
                <span asp-validation-for="PlateNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfSeats" class="control-label"></label>
                <input asp-for="NumberOfSeats" class="form-control" />
                <span asp-validation-for="NumberOfSeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="button" id="saveVehicleButton" value="Save" class="btn btn-success" /> |
                <a asp-action="Index" class="btn btn-primary">Back to List</a> |
                <a asp-action="EditDriver" asp-route-id="@Model.VehicleId" class="btn btn-primary">Edit Current Driver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        document.getElementById("saveVehicleButton").addEventListener("click", function () {
            var plateNumber = document.getElementById("plateNumberHidden").value;

            Swal.fire({
                title: 'Are you sure you want to edit this vehicle?',
                text: "Plate Number: " + plateNumber,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, save it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    document.getElementById("editVehicleForm").submit();
                }
            });
        });
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Vehicles/EditDriver.cshtml
@model EditDriverViewModel

@{
    ViewData["Title"] = "Edit Driver";
}

<h1>Edit Driver for car plate number: @ViewData["Platenb"]</h1>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
        {
            <p>@error.ErrorMessage</p>
        }
    </div>
}

<form id="editDriverForm" method="post">
    <input type="hidden" asp-for="VehicleId" />

    <div class="form-group">
        <label asp-for="SelectedDriverId" class="control-label">Select Driver by License Number</label>
        <select asp-for="SelectedDriverId" asp-items="Model.Drivers" class="form-control">
            <option value="0">-- No Driver --</option>
        </select>
        <span asp-validation-for="SelectedDriverId" class="text-danger"></span>
    </div>

    <br />

    <div class="form-group">
        <input type="button" value="Save" id="saveButton" class="btn btn-primary" />
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.VehicleId">Return To Edit</a>
    </div>
</form>

@section Scripts {
    <script>
        document.getElementById("saveButton").addEventListener("click", function () {
            var plateNumber = "@ViewData["Platenb"]";

            Swal.fire({
                title: 'Are you sure you want to change the current vehicle driver?',
                text: "Car plate number: " + plateNumber,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, save it!',
                cancelButtonText: 'Cancel'
            }).then((result) => {
                if (result.isConfirmed) {
                    document.getElementById("editDriverForm").submit();
                }
            });
        });
    </script>
}

Views/Vehicles/Index.cshtml
@model IEnumerable<CarManagement.Models.Vehicle>

@{
    ViewData["Title"] = "Vehicles";
}

<h1>Vehicles</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<table id="vehiclesTable" class="table">
    <thead>
        <tr>
            <th>Plate Number</th>
            <th>Number Of Seats</th>
            <th>Current Driver Licence NB</th>
            <th>Color</th>
            <th>Type</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.PlateNumber)</td>
                <td>@Html.DisplayFor(modelItem => item.NumberOfSeats)</td>
                <td>
                    @if (item.CurrentDriverId == null)
                    {
                        <span>No current</span>
                    }
                    else
                    {
                        <a asp-action="Details" asp-controller="Drivers" class="btn btn-link" asp-route-id="@item.CurrentDriverId">@Html.DisplayFor(modelItem => item.CurrentDriver.LicenseNumber)</a>

                    }
                </td>
                <td>@Html.DisplayFor(modelItem => item.Color)</td>
                <td>@Html.DisplayFor(modelItem => item.Type)</td>
                <td>
                    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.VehicleId">Edit</a> |
                    <a asp-action="Details" class="btn btn-success" asp-route-id="@item.VehicleId">Details</a> |
                    <a asp-controller="Maintenances" asp-action="MaintenancebyVehicle" class="btn btn-success" asp-route-id="@item.VehicleId">Maintenance</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.VehicleId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#vehiclesTable').DataTable();
        });
    </script>
}