Controllers/DriversController.cs
using Microsoft.AspNetCore.Mvc;
using CarManagement.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace CarManagement.Controllers
{
    [Authorize]
    public class DriversController : Controller
    {
        private readonly DriversRepository _repository;

        public DriversController(DriversRepository repository)
        {
            _repository = repository;
        }

        // GET: Drivers
        public async Task<IActionResult> Index()
        {
            IEnumerable<Driver> drivers = await _repository.GetAllDrivers();
            return View(drivers);
        }

        // GET: Drivers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _repository.Details(id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // GET: Drivers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Drivers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Driver driver)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _repository.Create(driver);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Show the error message to the user
                    ModelState.AddModelError(string.Empty, "A Driver with the same Licence Number already exists.");
                }
            }
            return View(driver);
        }

        // GET: Drivers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _repository.Details(id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // POST: Drivers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Driver driver)
        {
            if (id != driver.DriverId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await _repository.Edit(id, driver);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Show the error message to the user
                    ModelState.AddModelError(string.Empty, "A Driver with the same Licence Number already exists.");
                }
            }
            return View(driver);
        }

        // GET: Drivers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _repository.Details(id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _repository.Delete(id);
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/MaintenancesController.cs
using CarManagement.Models;
using CarManagement.Repositories;
using CarManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarManagement.Controllers
{
    [Authorize]
    public class MaintenancesController : Controller
    {
        private readonly MaintenanceRepository _maintenanceRepository;
        private readonly VehicleRepository _vehicleRepository;

        public MaintenancesController(MaintenanceRepository maintenanceRepository, VehicleRepository vehicleRepository)
        {
            _maintenanceRepository = maintenanceRepository;
            _vehicleRepository = vehicleRepository;
        }

        // GET: Maintenances
        public async Task<IActionResult> Index()
        {
            var maintenances = await _maintenanceRepository.GetAllMaintenances();
            return View(maintenances);
        }

        public async Task<IActionResult> MaintenancebyVehicle(int id)
        {
            var vehicle = await _vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            var maintenances = await _maintenanceRepository.GetAllMaintenancesByVehicleId(id);
            var viewModel = new MaintenancesViewModel
            {
                VehicleId = id,
                maintenances = maintenances
            };
            ViewData["Vehiclepltnb"] = vehicle.PlateNumber;
            return View("MaintenancebyId", viewModel);
        }

        // GET: Maintenances/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenance = await _maintenanceRepository.GetMaintenanceDetails(id);
            if (maintenance == null)
            {
                return NotFound();
            }

            return View(maintenance);
        }

        // GET: Maintenances/Create/1
        public async Task<IActionResult> Create(int id)
        {
            var vehicle = await _vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            ViewBag.Vehicles = new SelectList(await _vehicleRepository.GetallVehicles(), "VehicleId", "PlateNumber");
            var model = new MaintenancesViewModel
            {
                VehicleId = id,
                maintenance = new Maintenance(),
                maintenances = new List<Maintenance>()
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MaintenancesViewModel model)
        {
            if (ModelState.IsValid)
            {
                var vehicle = await _vehicleRepository.Details(model.VehicleId);
                if (vehicle == null)
                {
                    return NotFound();
                }

                var maintenance = new Maintenance
                {
                    Description = model.maintenance.Description,
                    DateOfMaintenance = model.maintenance.DateOfMaintenance,
                    Cost = model.maintenance.Cost,
                    VehicleId = model.VehicleId
                };

                await _maintenanceRepository.CreateMaintenance(maintenance);

                return RedirectToAction(nameof(MaintenancebyVehicle), new { id = maintenance.VehicleId });
            }

            return View(model);
        }

        // GET: Maintenances/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenance = await _maintenanceRepository.GetMaintenanceDetails(id);
            if (maintenance == null)
            {
                return NotFound();
            }

            ViewData["VehicleId"] = new SelectList(await _vehicleRepository.GetallVehicles(), "VehicleId", "PlateNumber", maintenance.VehicleId);
            return View(maintenance);
        }

        // POST: Maintenances/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Maintenance maintenance)
        {
            if (id != maintenance.MaintenanceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _maintenanceRepository.EditMaintenance(id, maintenance);
                return RedirectToAction(nameof(MaintenancebyVehicle), new { id = maintenance.VehicleId });
            }

            ViewData["VehicleId"] = new SelectList(await _vehicleRepository.GetallVehicles(), "VehicleId", "PlateNumber", maintenance.VehicleId);
            return View("MaintenancebyId", maintenance);
        }

        // GET: Maintenances/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenance = await _maintenanceRepository.GetMaintenanceDetails(id);
            if (maintenance == null)
            {
                return NotFound();
            }

            return View(maintenance);
        }

        // POST: Maintenances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var maintenance = await _maintenanceRepository.GetMaintenanceDetails(id);

            if (ModelState.IsValid)
            {
                await _maintenanceRepository.DeleteMaintenance(id);
            }

            return RedirectToAction(nameof(MaintenancebyVehicle), new { id = maintenance.VehicleId });
        }
    }
}

Controllers/VehiclesController.cs
using Microsoft.AspNetCore.Mvc;
using CarManagement.Data;
using CarManagement.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace CarManagement.Controllers
{
    [Authorize]
    public class VehiclesController : Controller
    {
        private readonly VehicleRepository vehicleRepository;
        private readonly DriversRepository driversRepository;

        public VehiclesController(VehicleRepository vehicleRepository, DriversRepository driversRepository)
        {
            this.vehicleRepository = vehicleRepository;
            this.driversRepository = driversRepository;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            var vehicles = await vehicleRepository.GetallVehicles();
            return View(vehicles);
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehicles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await vehicleRepository.Create(vehicle);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Show the error message to the user
                    ModelState.AddModelError(string.Empty, "A vehicle with the same Plate Number already exists.");
                }
            }
            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Vehicle vehicle)
        {
            if (id != vehicle.VehicleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await vehicleRepository.Edit(id, vehicle);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Show the error message to the user
                    ModelState.AddModelError(string.Empty, "A vehicle with the same Plate Number already exists.");
                }
            }
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await vehicleRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        // GET: Vehicles/EditDriver/5
        public async Task<IActionResult> EditDriver(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await vehicleRepository.Details(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            var drivers = await driversRepository.GetAllDrivers();

            ViewData["Platenb"] = vehicle.PlateNumber;

            var viewModel = new EditDriverViewModel
            {
                VehicleId = vehicle.VehicleId,
                SelectedDriverId = vehicle.CurrentDriverId.HasValue ? vehicle.CurrentDriverId.Value : 0,
                Drivers = new SelectList(drivers, "DriverId", "LicenseNumber")
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditDriver(EditDriverViewModel model)
        {


            var vehicle = await vehicleRepository.Details(model.VehicleId);
            if (vehicle == null)
            {
                return NotFound();
            }
            if (model.SelectedDriverId != vehicle.CurrentDriverId)
            {


                try
                {
                    await vehicleRepository.UpdateDriver(model.VehicleId, model.SelectedDriverId);
                    return Redirect($"/VehicleDriverHistories/HistorybyvehicleId/{model.VehicleId}");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "An error occurred while updating the driver.");
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "The selected driver is already the current driver.");
            }


            ViewData["Platenb"] = vehicle.PlateNumber;

            var drivers = await driversRepository.GetAllDrivers();

            model.Drivers = new SelectList(drivers, "DriverId", "LicenseNumber");
            return View(model);
        }

    }
}

Views/Home/Index.cshtml
@model CarManagement.Models.DashboardViewModel

@{
    var userName = User.Identity.IsAuthenticated ? User.Identity.Name : null;
}

<div class="container mt-4">
    <!-- Greeting -->
    <h1>
        @if (userName != null)
        {
            @($"Hello, {userName}!")
        }
        else
        {
            @("Welcome to the Dashboard!")
        }
    </h1>

    <!-- Dashboard Cards -->
    <div class="row">
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3">
                <div class="card-header">Total Vehicles</div>
                <div class="card-body">
                    <h5 class="card-title">@Model.TotalCars</h5>
                    <a href="@Url.Action("Index", "Vehicles")" class="btn btn-light">View Vehicles</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-success mb-3">
                <div class="card-header">Total Drivers</div>
                <div class="card-body">
                    <h5 class="card-title">@Model.TotalDrivers</h5>
                    <a href="@Url.Action("Index", "Drivers")" class="btn btn-light">View Drivers</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-warning mb-3">
                <div class="card-header">Total Maintenances</div>
                <div class="card-body">
                    <h5 class="card-title">@Model.TotalMaintenances</h5>
                    <a href="@Url.Action("Index", "Maintenances")" class="btn btn-light">View Maintenances</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card text-white bg-info mb-3">
                <div class="card-header">Active Vehicles</div>
                <div class="card-body">
                    <h5 class="card-title">@Model.ActiveVehicles</h5>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card text-white bg-danger mb-3">
                <div class="card-header">Inactive Vehicles</div>
                <div class="card-body">
                    <h5 class="card-title">@Model.InactiveVehicles</h5>
                </div>
            </div>
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <div class="col-md-12">
                <div class="card mb-3">
                    <div class="card-header">Total Maintenance Cost</div>
                    <div class="card-body">
                        <h5 class="card-title">$@Model.TotalMaintenanceCost</h5>
                    </div>
                </div>
            </div>
        }
    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <!-- Last 5 Maintenances Table -->
        <div class="card mt-4">
            <div class="card-header">Last 5 Maintenances</div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Vehicle</th>
                            <th>Cost</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.LastFiveMaintenances.Count() && i < 5; i++)
                        {
                            var maintenance = Model.LastFiveMaintenances.ElementAt(i);
                            <tr>
                                <td>@maintenance.DateOfMaintenance.ToShortDateString()</td>
                                <td>@maintenance.Vehicle?.PlateNumber</td>
                                <td>$@maintenance.Cost</td>
                                <td>@maintenance.Description</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
    }
    else
    {
        <a class=" btn btn-link" id="login" asp-area="Identity" asp-page="/Account/Login">Login To see More info</a>

    }
</div>